name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:

  build_sidecars:
    runs-on: ubuntu-latest
    env:
      VERSION: 6.25.0
      TAG: xroad-security-server-sidecar
      INSTANCE_COUNTRY: is
      
    steps:
    - uses: actions/checkout@v2

    - name: Build sidecar images with docker-build.sh
      run: |
        cd sidecar
        ./docker-build.sh 6.25.0 ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar is
        docker images

    - name: Push icelandic sidecar images to container registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar:6.25.0-secondary-is
        docker push ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar:6.25.0-primary-is
        docker push ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar:6.25.0-slim-secondary-is
        docker push ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar:6.25.0-slim-primary-is
        docker push ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar:6.25.0-is
        docker push ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar:6.25.0-slim-is
