name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_sidecars:
    runs-on: ubuntu-latest
    env:
      VERSION: 6.25.0
      TAG: xroad-security-server-sidecar
      INSTANCE_COUNTRY: is
    steps:
    - uses: actions/checkout@v2

    - name: Build slim
      run: |
        cd sidecar
        docker build -f ./slim/Dockerfile --build-arg "VERSION=${{ env.VERSION }}" --build-arg "TAG=${{ env.TAG }}" -t "ghcr.io/digitaliceland/x-road-security-server-sidecar/${{ env.TAG }}:${{ env.VERSION }}-slim"
        docker images


    - name: Build slim-is
      run: |
        pwd
        docker build -f ./slim/is/Dockerfile --build-arg "VERSION=${{ env.VERSION }}" --build-arg "TAG=${{ env.TAG }}" -t "ghcr.io/digitaliceland/x-road-security-server-sidecar/${{ env.TAG }}:${{ env.VERSION }}-slim-${{ env.INSTANCE_COUNTRY }}"
        docker images

#    - name: Build the Docker image test 1
#      run: |
#        #docker build -f sidecar/slim/${{ env.INSTANCE_COUNTRY }}/Dockerfile --build-arg "VERSION=${{ env.VERSION }}" --build-arg "TAG=${{ env.TAG }}" -t "ghcr.io/digitaliceland/x-road-security-server-sidecar/${{ env.TAG }}:${{ env.VERSION }}-slim-${{ env.INSTANCE_COUNTRY }}"
#        ./sidecar/docker-build.sh 6.25.0 ghcr.io/digitaliceland/x-road-security-server-sidecar/xroad-security-server-sidecar is
#        docker images
